# [Info] 基本信息
site_name: 长大地科研学课程记录【2022级】 # 左上角标题
site_url: https://github.com/gis-xh/yanxue-notes
site_author: gis-xh
site_description: 长大地科研学课程记录公开站【2022级】

# [UI] 界面设置
## [top]
theme:
  name: material
  palette: 
      - scheme: default # 默认日间模式
        primary: indigo # 上方的颜色为靛蓝色
        accent: orange # 链接等可交互元件的高亮色
        toggle:
          icon: material/weather-night # 图标
          name: 切换至夜间模式 # 鼠标悬浮提示
      - scheme: slate # 夜间模式
        primary: indigo
        accent: orange
        toggle:
          icon: material/weather-sunny
          name: 切换至日间模式
  features:
    - content.code.copy # 代码复制
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer # 页面底部上一个下一个按钮
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share # 将搜索结果分享
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github-alt
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/gis-xh/yanxue-notes # 右上角点击跳转的链接
repo_name: gis-xh/yanxue-notes # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2023 gis-xh # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    # - icon: fontawesome/brands/gitee
    #   link: https://gitee.com/gis-xh
    #   name: Gitee | gis-xh
    - icon: fontawesome/brands/github
      link: https://github.com/gis-xh
      name: GitHub | gis-xh # 鼠标悬浮提示

# [Navigtion] 导航栏
nav:
  - 空间数据库: 
    - SDB/index.md
    - PostgreSQL9.6 & PostGIS3.2 安装教程: SDB/Install-PostgreSQL+PostGIS.md
    - 课堂要求: SDB/class-requirement.md
    - 课后练习: 
      - 练习一 数字化校园: SDB/practice/01.md
      - 练习二 数字化校园的数据表与 E-R 图: SDB/practice/02.md
      - 练习三 SQL 的 6 个基本操作: SDB/practice/03.md
      - 练习四 论文研读: SDB/practice/04.md
      - 练习五 邻接矩阵: SDB/practice/05.md
  - 综合英语: 
    - 选词填空 (25分): English/words-in-use.md
    - 英翻汉 (30分): English/translation.md
    - 阅读 (30分): English/reading.md
    - 作文 (15分): English/writing-task.md
  - 遥感数字图像分析与处理: 
    - RS-DIP/index.md
    - 课后练习: 
      - 练习一: RS-DIP/practice/01.md
      - 练习二: RS-DIP/practice/02.md
      - 练习三: RS-DIP/practice/03.md
    - 结课大作业:
      - 基于 LT-GEE 的武汉市森林扰动地图制作: RS-DIP/practice/coursework.md
  - 大数据系列课程: 
    - BigData/index.md
    - 地质大数据课后练习:
      - 练习一 配置 Hadoop 环境: 
        - 虚拟机服务器版: BigData/GGBD/practice/01-aliyun.md
        - 阿里云服务器版: BigData/GGBD/practice/01-vm.md
      - 练习二 熟悉常用的 HBase 操作:
        - 准备工作: BigData/GGBD/practice/02-1.md
        - 熟悉常用的 HBase 操作 - 提交版: BigData/GGBD/practice/02-2.md
        - 熟悉常用的 HBase 操作 - 自制版: BigData/GGBD/practice/02-3.md
      - 练习三 安装 Jupyter 并运行 pyspark:
        - 安装 Jupyter 并运行 pyspark: BigData/GGBD/practice/03-1.md
        - MapReduce 编程初级实践: BigData/GGBD/practice/03-2.md
      - 练习四 安装并使用 MongoDB: BigData/GGBD/practice/04.md
      - 练习五 安装并使用 HIVE: BigData/GGBD/practice/05.md
    - 大数据理论与应用: BigData/BigData-reports.md
    - 数据分析与数据挖掘: BigData/DADM/notes.md
  - 土地信息系统:
    - LIS/index.md
    - 智慧城市空间信息服务平台时空数据建库: LIS/01.md
  - 地理信息系统三维建模:
    - GIS-3DM/index.md
    - 课堂实验报告: GIS-3DM/test-report.md



# [Extensions] 扩展
plugins:
  - search:
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
  - git-revision-date-localized: # 日期显示
      # ["date","datetime","iso_date","iso_datetime","timeago","custom"]
      type: timeago
      enable_creation_date: true # 创建时间
  - glightbox # 图像缩放
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - md_in_html
  - tables
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  - mkdocs/css/img-center.css # 图像居中